# Load Dataset

In [4]:
import pandas as pd

In [5]:
df= pd.read_csv("/content/gk_qna_dataset.csv")

In [6]:
df

                                              question   answer
0                     What is the capital of "France"?    Paris
1                    What is the capital of "Germany"?   Berlin
2                      What is the capital of "Italy"?     Rome
3                      What is the capital of "Spain"?   Madrid
4                      What is the capital of "Japan"?    Tokyo
..                                                 ...      ...
166          Can you tell me, "Which bird cannot fly"?  Ostrich
167  I was wondering, "What is 'H2O' commonly called"?    Water
168  I was wondering, "Which planet is known as the...     Mars
169  Can you tell me, "What is the main religion in...    Islam
170  Quick question: "Which animal is known for loy...      Dog

[171 rows x 2 columns]

In [7]:
df.head()

                            question  answer
0   What is the capital of "France"?   Paris
1  What is the capital of "Germany"?  Berlin
2    What is the capital of "Italy"?    Rome
3    What is the capital of "Spain"?  Madrid
4    What is the capital of "Japan"?   Tokyo

In [8]:
df["question"][0]

'What is the capital of "France"?'

# tokenize

In [9]:
import re

def tokenize(text):

  #1  Lowercase
  text = text.lower()

  #2 remove quotes
  text = re.sub( r"[\"']","",text)


  #3 remove all punctuations
  text = re.sub(r"[^a-z0-9\s]", " ", text)

  #4 remove extra space
  text = re.sub(r"\s+", " ", text).strip()

  #tokenize split into words
  tokens = text.split()

  return tokens

In [10]:
print(tokenize(df["question"][0]))

['what', 'is', 'the', 'capital', 'of', 'france']

# Vocab forming

In [11]:
vocab = {'<UNK>':0}

In [23]:
def build_vocab(row):
  print(row["question"], row["answer"])


  tokenized_question= tokenize(row["question"])
  tokenized_answer= tokenize(row["answer"])

  #print(tokeniz_question, tokeniz_answer)

  merged_tokens = tokenized_question + tokenized_answer
  # print(merged_tokens)

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [24]:
df.apply(build_vocab, axis=1)

What is the capital of "France"? Paris
What is the capital of "Germany"? Berlin
What is the capital of "Italy"? Rome
What is the capital of "Spain"? Madrid
What is the capital of "Japan"? Tokyo
What is the capital of "Canada"? Ottawa
What is the capital of "Brazil"? Brasilia
What is the capital of "Australia"? Canberra
What is the capital of "India"? New Delhi
What is the capital of "China"? Beijing
What is the capital of "Russia"? Moscow
What is the capital of "United States"? Washington DC
What is the capital of "Mexico"? Mexico City
What is the capital of "Egypt"? Cairo
What is the capital of "Turkey"? Ankara
What is the capital of "Argentina"? Buenos Aires
What is the capital of "South Korea"? Seoul
What is the capital of "Indonesia"? Jakarta
What is the capital of "Pakistan"? Islamabad
What is the capital of "Bangladesh"? Dhaka
What is the capital of "Nepal"? Kathmandu
What is the capital of "Sri Lanka"? Colombo
What is the capital of "Thailand"? Bangkok
What is the capital of "Malaysia"? Kuala Lumpur
What is the capital of "Vietnam"? Hanoi
What is the capital of "UAE"? Abu Dhabi
What is the capital of "Iran"? Tehran
What is the capital of "Iraq"? Baghdad
What is the capital of "Saudi Arabia"? Riyadh
What is the capital of "Nigeria"? Abuja
What is the capital of "Kenya"? Nairobi
What is the capital of "Chile"? Santiago
Who discovered 'gravity'? Isaac Newton
Who invented the 'telephone'? Alexander Graham Bell
What is 'H2O' commonly called? Water
Which gas do plants absorb? Carbon dioxide
Which planet is known as the 'Red Planet'? Mars
Who painted the 'Mona Lisa'? Leonardo da Vinci
What is the largest ocean? Pacific Ocean
Who developed the 'theory of relativity'? Albert Einstein
What is 'AI' short for? Artificial Intelligence
What is 'ML' short for? Machine Learning
What is 'NLP' short for? Natural Language Processing
What does 'CPU' stand for? Central Processing Unit
What is 'RAM'? Computer memory
What does 'GPU' stand for? Graphics Processing Unit
What is a 'URL'? Web address
What does 'HTTP' stand for? HyperText Transfer Protocol
What is 'JSON' used for? Data exchange
What is 'SQL'? Database query language
What does 'API' mean? Application Programming Interface
Who invented the 'light bulb'? Thomas Edison
Who invented the 'airplane'? Wright Brothers
Who discovered 'penicillin'? Alexander Fleming
Who wrote 'Hamlet'? William Shakespeare
Who wrote 'Harry Potter'? J K Rowling
Which country is known as the 'Land of Rising Sun'? Japan
Which animal is called the 'King of Jungle'? Lion
Which animal is the largest on Earth? Blue Whale
Which bird cannot fly? Ostrich
Which animal is known for loyalty? Dog
Which fruit is typically red? Apple
Which fruit is yellow? Banana
Which organ pumps blood? Heart
Which gas do humans breathe? Oxygen
Which metal is liquid at room temperature? Mercury
Which instrument measures temperature? Thermometer
Which instrument measures pressure? Barometer
What is the main language of Brazil? Portuguese
What is the main language of Spain? Spanish
What is the main religion in Saudi Arabia? Islam
What is the national animal of Bangladesh? Royal Bengal Tiger
Quick question: "Who invented the 'light bulb'"? Thomas Edison
"Who discovered 'penicillin'" — do you know? Alexander Fleming
Do you know, "What is the largest ocean"? Pacific Ocean
I was wondering, "What is a 'URL'"? Web address
Hey, what about this: "Which instrument measures pressure"? Barometer
"Who invented the 'telephone'" — do you know? Alexander Graham Bell
I was wondering, "Who invented the 'light bulb'"? Thomas Edison
Quick question: "What is the main language of Spain"? Spanish
Hey, what about this: "What is a 'URL'"? Web address
I was wondering, "Which gas do humans breathe"? Oxygen
I was wondering, "Which organ pumps blood"? Heart
Hey, what about this: "What is the largest ocean"? Pacific Ocean
Do you know, "Who invented the 'telephone'"? Alexander Graham Bell
Quick question: "Who wrote 'Hamlet'"? William Shakespeare
"Which instrument measures pressure" — do you know? Barometer
Can you tell me, "What is the national animal of Bangladesh"? Royal Bengal Tiger
Quick question: "What is the main language of Brazil"? Portuguese
Hey, what about this: "Who developed the 'theory of relativity'"? Albert Einstein
Hey, what about this: "What is 'AI' short for"? Artificial Intelligence
I was wondering, "Which animal is known for loyalty"? Dog
Do you know, "What is a 'URL'"? Web address
Quick question: "Which gas do plants absorb"? Carbon dioxide
I was wondering, "Who invented the 'telephone'"? Alexander Graham Bell
Do you know, "Which fruit is yellow"? Banana
Can you tell me, "Which planet is known as the 'Red Planet'"? Mars
Do you know, "Which gas do plants absorb"? Carbon dioxide
Can you tell me, "What does 'CPU' stand for"? Central Processing Unit
Hey, what about this: "Who wrote 'Harry Potter'"? J K Rowling
Do you know, "What does 'GPU' stand for"? Graphics Processing Unit
Quick question: "Which gas do humans breathe"? Oxygen
I was wondering, "What is 'RAM'"? Computer memory
Can you tell me, "What is the largest ocean"? Pacific Ocean
Quick question: "Which metal is liquid at room temperature"? Mercury
Quick question: "What is 'ML' short for"? Machine Learning
Hey, what about this: "Which fruit is yellow"? Banana
Hey, what about this: "Which instrument measures temperature"? Thermometer
"Which animal is the largest on Earth" — do you know? Blue Whale
"What is the largest ocean" — do you know? Pacific Ocean
"Which organ pumps blood" — do you know? Heart
Can you tell me, "Who wrote 'Hamlet'"? William Shakespeare
Do you know, "What is the main language of Brazil"? Portuguese
"Who painted the 'Mona Lisa'" — do you know? Leonardo da Vinci
Do you know, "Which country is known as the 'Land of Rising Sun'"? Japan
Quick question: "Which animal is called the 'King of Jungle'"? Lion
Can you tell me, "Which fruit is yellow"? Banana
Can you tell me, "Who invented the 'light bulb'"? Thomas Edison
Quick question: "Who discovered 'penicillin'"? Alexander Fleming
I was wondering, "Who wrote 'Harry Potter'"? J K Rowling
"What is the national animal of Bangladesh" — do you know? Royal Bengal Tiger
Hey, what about this: "Which gas do plants absorb"? Carbon dioxide
I was wondering, "What is 'JSON' used for"? Data exchange
Can you tell me, "Who discovered 'gravity'"? Isaac Newton
I was wondering, "Who invented the 'airplane'"? Wright Brothers
Do you know, "Who invented the 'light bulb'"? Thomas Edison
Can you tell me, "Which gas do humans breathe"? Oxygen
Hey, what about this: "What is 'H2O' commonly called"? Water
Quick question: "What does 'GPU' stand for"? Graphics Processing Unit
Hey, what about this: "Who discovered 'gravity'"? Isaac Newton
Can you tell me, "What is a 'URL'"? Web address
I was wondering, "What does 'API' mean"? Application Programming Interface
Can you tell me, "What is 'RAM'"? Computer memory
Can you tell me, "What is 'AI' short for"? Artificial Intelligence
Quick question: "Who wrote 'Harry Potter'"? J K Rowling
Hey, what about this: "Who discovered 'penicillin'"? Alexander Fleming
Do you know, "What is 'H2O' commonly called"? Water
Do you know, "What is 'ML' short for"? Machine Learning
I was wondering, "What is 'NLP' short for"? Natural Language Processing
Do you know, "Which bird cannot fly"? Ostrich
Do you know, "Which metal is liquid at room temperature"? Mercury
"Which planet is known as the 'Red Planet'" — do you know? Mars
Hey, what about this: "Which animal is the largest on Earth"? Blue Whale
"Which bird cannot fly" — do you know? Ostrich
Can you tell me, "What is 'ML' short for"? Machine Learning
I was wondering, "What does 'CPU' stand for"? Central Processing Unit
Do you know, "What is the main religion in Saudi Arabia"? Islam
Do you know, "Who wrote 'Hamlet'"? William Shakespeare
Can you tell me, "What is 'H2O' commonly called"? Water
I was wondering, "Who wrote 'Hamlet'"? William Shakespeare
Hey, what about this: "Which planet is known as the 'Red Planet'"? Mars
"Who invented the 'light bulb'" — do you know? Thomas Edison
Quick question: "What is the largest ocean"? Pacific Ocean
Hey, what about this: "Who painted the 'Mona Lisa'"? Leonardo da Vinci
I was wondering, "What is 'ML' short for"? Machine Learning
Hey, what about this: "What does 'HTTP' stand for"? HyperText Transfer Protocol
Hey, what about this: "Who invented the 'telephone'"? Alexander Graham Bell
"Which country is known as the 'Land of Rising Sun'" — do you know? Japan
Quick question: "Which country is known as the 'Land of Rising Sun'"? Japan
Do you know, "Who wrote 'Harry Potter'"? J K Rowling
Hey, what about this: "What is 'RAM'"? Computer memory
Quick question: "Who invented the 'telephone'"? Alexander Graham Bell
Quick question: "Which organ pumps blood"? Heart
Hey, what about this: "What does 'CPU' stand for"? Central Processing Unit
Can you tell me, "Which instrument measures pressure"? Barometer
I was wondering, "Which country is known as the 'Land of Rising Sun'"? Japan
Can you tell me, "Which bird cannot fly"? Ostrich
I was wondering, "What is 'H2O' commonly called"? Water
I was wondering, "Which planet is known as the 'Red Planet'"? Mars
Can you tell me, "What is the main religion in Saudi Arabia"? Islam
Quick question: "Which animal is known for loyalty"? Dog

0      None
1      None
2      None
3      None
4      None
       ...
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [25]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq': 68,
 'baghdad': 69,
 'saudi': 70,
 'arabia': 71,
 'riyadh': 72,
 'nigeria': 73,
 'abuja': 74,
 'kenya': 75,
 'nairobi': 76,
 'chile': 77,
 'santiago': 78,
 'who': 79,
 'discovered': 80,
 'gravity': 81,
 'isaac': 82,
 'newton': 83,
 'invented': 84,
 'telephone': 85,
 'alexander': 86,
 'graham': 87,
 'bell': 88,
 'h2o': 89,
 'commonly': 90,
 'called': 91,
 'water': 92,
 'which': 93,
 'gas': 94,
 'do': 95,
 'plants': 96,
 'absorb': 97,
 'carbon': 98,
 'dioxide': 99,
 'planet': 100,
 'known': 101,
 'as': 102,
 'red': 103,
 'mars': 104,
 'painted': 105,
 'mona': 106,
 'lisa': 107,
 'leonardo': 108,
 'da': 109,
 'vinci': 110,
 'largest': 111,
 'ocean': 112,
 'pacific': 113,
 'developed': 114,
 'theory': 115,
 'relativity': 116,
 'albert': 117,
 'einstein': 118,
 'ai': 119,
 'short': 120,
 'for': 121,
 'artificial': 122,
 'intelligence': 123,
 'ml': 124,
 'machine': 125,
 'learning': 126,
 'nlp': 127,
 'natural': 128,
 'language': 129,
 'processing': 130,
 'does': 131,
 'cpu': 132,
 'stand': 133,
 'central': 134,
 'unit': 135,
 'ram': 136,
 'computer': 137,
 'memory': 138,
 'gpu': 139,
 'graphics': 140,
 'a': 141,
 'url': 142,
 'web': 143,
 'address': 144,
 'http': 145,
 'hypertext': 146,
 'transfer': 147,
 'protocol': 148,
 'json': 149,
 'used': 150,
 'data': 151,
 'exchange': 152,
 'sql': 153,
 'database': 154,
 'query': 155,
 'api': 156,
 'mean': 157,
 'application': 158,
 'programming': 159,
 'interface': 160,
 'light': 161,
 'bulb': 162,
 'thomas': 163,
 'edison': 164,
 'airplane': 165,
 'wright': 166,
 'brothers': 167,
 'penicillin': 168,
 'fleming': 169,
 'wrote': 170,
 'hamlet': 171,
 'william': 172,
 'shakespeare': 173,
 'harry': 174,
 'potter': 175,
 'j': 176,
 'k': 177,
 'rowling': 178,
 'country': 179,
 'land': 180,
 'rising': 181,
 'sun': 182,
 'animal': 183,
 'king': 184,
 'jungle': 185,
 'lion': 186,
 'on': 187,
 'earth': 188,
 'blue': 189,
 'whale': 190,
 'bird': 191,
 'cannot': 192,
 'fly': 193,
 'ostrich': 194,
 'loyalty': 195,
 'dog': 196,
 'fruit': 197,
 'typically': 198,
 'apple': 199,
 'yellow': 200,
 'banana': 201,
 'organ': 202,
 'pumps': 203,
 'blood': 204,
 'heart': 205,
 'humans': 206,
 'breathe': 207,
 'oxygen': 208,
 'metal': 209,
 'liquid': 210,
 'at': 211,
 'room': 212,
 'temperature': 213,
 'mercury': 214,
 'instrument': 215,
 'measures': 216,
 'thermometer': 217,
 'pressure': 218,
 'barometer': 219,
 'main': 220,
 'portuguese': 221,
 'spanish': 222,
 'religion': 223,
 'in': 224,
 'islam': 225,
 'national': 226,
 'royal': 227,
 'bengal': 228,
 'tiger': 229,
 'quick': 230,
 'question': 231,
 'you': 232,
 'know': 233,
 'i': 234,
 'was': 235,
 'wondering': 236,
 'hey': 237,
 'about': 238,
 'this': 239,
 'can': 240,
 'tell': 241,
 'me': 242}

In [26]:
len(vocab)

243

In [27]:
vocab['what']

1

# text to indices

In [28]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    # print(token)
    if token in vocab:
      # print(vocab[token])
      indexed_text.append(vocab[token])

    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [29]:
text_to_indices("the is Phitron",vocab)

[3, 2, 0]

# Dataset and Dataloader

In [30]:
import torch
from torch.utils.data import Dataset,DataLoader

In [31]:
df.shape[0]

171

In [32]:
index = 0

text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [33]:
class QADataset(Dataset):

  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [34]:
dataset = QADataset(df,vocab)

In [35]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 8]), tensor([9]))

In [36]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [37]:
for question,answer in dataloader:
  print(question,answer[0])

tensor([[237,   1, 238, 239,   1, 131, 145, 133, 121]]) tensor([146, 147, 148])
tensor([[ 1,  2,  3,  4,  5, 12]]) tensor([13])
tensor([[ 95, 232, 233,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[240, 232, 241, 242,  93,  94,  95, 206, 207]]) tensor([208])
tensor([[  1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[ 1,  2,  3,  4,  5, 20]]) tensor([21])
tensor([[237,   1, 238, 239,   1,   2, 136]]) tensor([137, 138])
tensor([[  1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[  1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[230, 231,   1,   2,   3, 220, 129,   5,  12]]) tensor([222])
tensor([[240, 232, 241, 242,  93, 197,   2, 200]]) tensor([201])
tensor([[ 1,  2,  3,  4,  5, 45]]) tensor([46])
tensor([[234, 235, 236,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[ 1,  2,  3,  4,  5, 75]]) tensor([76])
tensor([[93, 94, 95, 96, 97]]) tensor([98, 99])
tensor([[230, 231,   1, 131, 139, 133, 121]]) tensor([140, 130, 135])
tensor([[234, 235, 236,  79, 170, 171]]) tensor([172, 173])
tensor([[234, 235, 236,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 1,  2,  3,  4,  5, 58]]) tensor([59, 60])
tensor([[ 79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[234, 235, 236,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 1,  2,  3,  4,  5, 35]]) tensor([36])
tensor([[ 95, 232, 233,  93, 197,   2, 200]]) tensor([201])
tensor([[240, 232, 241, 242,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[240, 232, 241, 242,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[ 93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[  1,   2,   3, 226, 183,   5,  49,  95, 232, 233]]) tensor([227, 228, 229])
tensor([[237,   1, 238, 239,  79, 114,   3, 115,   5, 116]]) tensor([117, 118])
tensor([[ 1,  2,  3,  4,  5, 66]]) tensor([67])
tensor([[230, 231,   1,   2,   3, 220, 129,   5,  18]]) tensor([221])
tensor([[  1, 131, 156, 157]]) tensor([158, 159, 160])
tensor([[234, 235, 236,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[234, 235, 236,   1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[ 93, 183,   2,   3, 111, 187, 188,  95, 232, 233]]) tensor([189, 190])
tensor([[237,   1, 238, 239,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[  1,   2, 119, 120, 121]]) tensor([122, 123])
tensor([[79, 84,  3, 85]]) tensor([86, 87, 88])
tensor([[230, 231,  93, 183,   2,  91,   3, 184,   5, 185]]) tensor([186])
tensor([[237,   1, 238, 239,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[  1,   2, 136]]) tensor([137, 138])
tensor([[240, 232, 241, 242,  79, 170, 171]]) tensor([172, 173])
tensor([[  1,   2,   3, 226, 183,   5,  49]]) tensor([227, 228, 229])
tensor([[240, 232, 241, 242,  93, 215, 216, 218]]) tensor([219])
tensor([[  1,   2, 149, 150, 121]]) tensor([151, 152])
tensor([[240, 232, 241, 242,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 95, 232, 233,  93, 191, 192, 193]]) tensor([194])
tensor([[ 93, 202, 203, 204,  95, 232, 233]]) tensor([205])
tensor([[ 1,  2,  3,  4,  5, 22]]) tensor([23, 24])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[ 1,  2, 89, 90, 91]]) tensor([92])
tensor([[230, 231,  93,  94,  95,  96,  97]]) tensor([98, 99])
tensor([[230, 231,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[ 95, 232, 233,   1,   2,   3, 220, 129,   5,  18]]) tensor([221])
tensor([[  1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 1,  2,  3,  4,  5, 18]]) tensor([19])
tensor([[ 95, 232, 233,  93, 209,   2, 210, 211, 212, 213]]) tensor([214])
tensor([[234, 235, 236,   1,   2, 127, 120, 121]]) tensor([128, 129, 130])
tensor([[ 1,  2,  3,  4,  5, 56]]) tensor([57])
tensor([[237,   1, 238, 239,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[237,   1, 238, 239,  93,  94,  95,  96,  97]]) tensor([98, 99])
tensor([[ 93, 215, 216, 213]]) tensor([217])
tensor([[230, 231,  93, 209,   2, 210, 211, 212, 213]]) tensor([214])
tensor([[79, 80, 81]]) tensor([82, 83])
tensor([[240, 232, 241, 242,  93, 191, 192, 193]]) tensor([194])
tensor([[234, 235, 236,   1,   2, 149, 150, 121]]) tensor([151, 152])
tensor([[240, 232, 241, 242,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[237,   1, 238, 239,   1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[ 93, 191, 192, 193,  95, 232, 233]]) tensor([194])
tensor([[ 79,  84,   3,  85,  95, 232, 233]]) tensor([86, 87, 88])
tensor([[ 79,  84,   3, 161, 162,  95, 232, 233]]) tensor([163, 164])
tensor([[237,   1, 238, 239,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 93, 202, 203, 204]]) tensor([205])
tensor([[ 93, 191, 192, 193]]) tensor([194])
tensor([[234, 235, 236,   1,   2, 136]]) tensor([137, 138])
tensor([[240, 232, 241, 242,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[234, 235, 236,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 1,  2,  3,  4,  5, 63]]) tensor([64, 65])
tensor([[ 95, 232, 233,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[ 1,  2,  3,  4,  5, 49]]) tensor([50])
tensor([[234, 235, 236,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[234, 235, 236,  93, 202, 203, 204]]) tensor([205])
tensor([[ 93, 100,   2, 101, 102,   3, 103, 100,  95, 232, 233]]) tensor([104])
tensor([[ 79, 170, 171]]) tensor([172, 173])
tensor([[ 79,  84,   3, 165]]) tensor([166, 167])
tensor([[240, 232, 241, 242,   1,   2, 119, 120, 121]]) tensor([122, 123])
tensor([[237,   1, 238, 239,  79, 105,   3, 106, 107]]) tensor([108, 109, 110])
tensor([[237,   1, 238, 239,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[230, 231,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[ 93, 183,   2, 101, 121, 195]]) tensor([196])
tensor([[237,   1, 238, 239,  79,  80, 168]]) tensor([ 86, 169])
tensor([[ 95, 232, 233,  79, 170, 171]]) tensor([172, 173])
tensor([[ 95, 232, 233,   1, 131, 139, 133, 121]]) tensor([140, 130, 135])
tensor([[237,   1, 238, 239,  93, 197,   2, 200]]) tensor([201])
tensor([[ 93, 183,   2,   3, 111, 187, 188]]) tensor([189, 190])
tensor([[ 1,  2,  3,  4,  5, 53, 54]]) tensor([55])
tensor([[  1,   2,   3, 220, 129,   5,  18]]) tensor([221])
tensor([[240, 232, 241, 242,   1,   2,   3, 220, 223, 224,  70,  71]]) tensor([225])
tensor([[  1,   2,   3, 111, 112,  95, 232, 233]]) tensor([113, 112])
tensor([[237,   1, 238, 239,  93, 215, 216, 213]]) tensor([217])
tensor([[240, 232, 241, 242,   1,   2,   3, 226, 183,   5,  49]]) tensor([227, 228, 229])
tensor([[234, 235, 236,   1, 131, 156, 157]]) tensor([158, 159, 160])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 93, 197,   2, 200]]) tensor([201])
tensor([[ 93, 183,   2,  91,   3, 184,   5, 185]]) tensor([186])
tensor([[234, 235, 236,  93, 183,   2, 101, 121, 195]]) tensor([196])
tensor([[ 1,  2,  3,  4,  5, 70, 71]]) tensor([72])
tensor([[ 95, 232, 233,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 1,  2,  3,  4,  5, 77]]) tensor([78])
tensor([[ 93, 215, 216, 218,  95, 232, 233]]) tensor([219])
tensor([[230, 231,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[ 95, 232, 233,  93,  94,  95,  96,  97]]) tensor([98, 99])
tensor([[240, 232, 241, 242,   1,   2, 136]]) tensor([137, 138])
tensor([[ 1,  2,  3,  4,  5, 42, 43]]) tensor([44])
tensor([[ 93, 209,   2, 210, 211, 212, 213]]) tensor([214])
tensor([[234, 235, 236,  79,  84,   3, 165]]) tensor([166, 167])
tensor([[230, 231,  93, 183,   2, 101, 121, 195]]) tensor([196])
tensor([[ 1,  2,  3,  4,  5, 47]]) tensor([48])
tensor([[ 1,  2,  3,  4,  5, 25]]) tensor([26])
tensor([[230, 231,  79, 170, 171]]) tensor([172, 173])
tensor([[ 95, 232, 233,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[ 93,  94,  95, 206, 207]]) tensor([208])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182,  95, 232, 233]]) tensor([14])
tensor([[ 79,  80, 168,  95, 232, 233]]) tensor([ 86, 169])
tensor([[  1,   2, 153]]) tensor([154, 155, 129])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[ 1,  2,  3,  4,  5, 16]]) tensor([17])
tensor([[ 1,  2,  3,  4,  5, 37]]) tensor([38])
tensor([[234, 235, 236,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[ 79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 79, 105,   3, 106, 107,  95, 232, 233]]) tensor([108, 109, 110])
tensor([[  1, 131, 145, 133, 121]]) tensor([146, 147, 148])
tensor([[ 95, 232, 233,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[230, 231,  79,  80, 168]]) tensor([ 86, 169])
tensor([[ 95, 232, 233,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 79,  80, 168]]) tensor([ 86, 169])
tensor([[240, 232, 241, 242,   1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[ 79, 114,   3, 115,   5, 116]]) tensor([117, 118])
tensor([[ 95, 232, 233,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[  1,   2, 127, 120, 121]]) tensor([128, 129, 130])
tensor([[ 93, 197,   2, 198, 103]]) tensor([199])
tensor([[ 1,  2,  3,  4,  5, 39]]) tensor([40, 41])
tensor([[230, 231,  93, 202, 203, 204]]) tensor([205])
tensor([[234, 235, 236,  93,  94,  95, 206, 207]]) tensor([208])
tensor([[230, 231,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 1,  2,  3,  4,  5, 29, 30]]) tensor([31, 32])
tensor([[237,   1, 238, 239,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[ 95, 232, 233,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 1,  2,  3,  4,  5, 68]]) tensor([69])
tensor([[ 1,  2,  3,  4,  5, 51]]) tensor([52])
tensor([[230, 231,  93,  94,  95, 206, 207]]) tensor([208])
tensor([[  1,   2,   3, 220, 129,   5,  12]]) tensor([222])
tensor([[237,   1, 238, 239,  79,  80,  81]]) tensor([82, 83])
tensor([[230, 231,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[237,   1, 238, 239,  93, 183,   2,   3, 111, 187, 188]]) tensor([189, 190])
tensor([[240, 232, 241, 242,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[ 1,  2,  3,  4,  5, 27]]) tensor([28])
tensor([[240, 232, 241, 242,  79,  80,  81]]) tensor([82, 83])
tensor([[ 79, 105,   3, 106, 107]]) tensor([108, 109, 110])
tensor([[237,   1, 238, 239,   1,   2, 119, 120, 121]]) tensor([122, 123])
tensor([[  1, 131, 139, 133, 121]]) tensor([140, 130, 135])
tensor([[  1,   2,   3, 220, 223, 224,  70,  71]]) tensor([225])
tensor([[237,   1, 238, 239,  93, 215, 216, 218]]) tensor([219])
tensor([[230, 231,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 93, 215, 216, 218]]) tensor([219])
tensor([[ 1,  2,  3,  4,  5, 14]]) tensor([15])
tensor([[234, 235, 236,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[ 1,  2,  3,  4,  5, 33]]) tensor([33, 34])
tensor([[ 95, 232, 233,   1,   2,   3, 220, 223, 224,  70,  71]]) tensor([225])
tensor([[ 1,  2,  3,  4,  5, 61]]) tensor([62])
tensor([[ 1,  2,  3,  4,  5, 10]]) tensor([11])

In [38]:
# squeeze

import torch

x = torch.tensor( [[[1,2,3]]] )

# print(x.shape)

y = x.squeeze(0)

print(y.shape)

torch.Size([1, 3])

# RNN Architecture Implementation

In [39]:
import torch.nn as nn

class simpleRNN(nn.Module):
  def __init__(self,vocab_size,embedding_dim=50,hidden_size=64):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size,embedding_dim)
    self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
    self.fc = nn.Linear(hidden_size,vocab_size)


  def forward(self,question):
     embedded = self.embedding(question) # (1, seq_len, 50)
     _,final = self.rnn(embedded)

     return self.fc(final.squeeze(0))  # (1, vocab_size)

In [40]:
model = simpleRNN(vocab_size = len(vocab))

In [41]:
# EXample of unsqueeze

import torch

x = torch.tensor([1, 2, 3])   # shape: (3,)
print(x.shape)

y = x.unsqueeze(0)
print(y.shape)

torch.Size([3])
torch.Size([1, 3])

# training loop

In [42]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.0001)
epochs = 50

In [43]:
for epoch in range(epochs):
    total_loss = 0
    for question, answer in dataloader:
        optimizer.zero_grad()
        output = model(question)
        # Fix: take only the first answer token as target → shape (1,)
        target = answer[0][0].unsqueeze(0)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}/{epochs}  |  Loss: {total_loss:.4f}")

Epoch  10/50  |  Loss: 592.2536
Epoch  20/50  |  Loss: 364.2504
Epoch  30/50  |  Loss: 243.4738
Epoch  40/50  |  Loss: 173.5436
Epoch  50/50  |  Loss: 124.1299

# Prediction

In [44]:
vocab.items()

dict_items([('<UNK>', 0), ('what', 1), ('is', 2), ('the', 3), ('capital', 4), ('of', 5), ('france', 6), ('paris', 7), ('germany', 8), ('berlin', 9), ('italy', 10), ('rome', 11), ('spain', 12), ('madrid', 13), ('japan', 14), ('tokyo', 15), ('canada', 16), ('ottawa', 17), ('brazil', 18), ('brasilia', 19), ('australia', 20), ('canberra', 21), ('india', 22), ('new', 23), ('delhi', 24), ('china', 25), ('beijing', 26), ('russia', 27), ('moscow', 28), ('united', 29), ('states', 30), ('washington', 31), ('dc', 32), ('mexico', 33), ('city', 34), ('egypt', 35), ('cairo', 36), ('turkey', 37), ('ankara', 38), ('argentina', 39), ('buenos', 40), ('aires', 41), ('south', 42), ('korea', 43), ('seoul', 44), ('indonesia', 45), ('jakarta', 46), ('pakistan', 47), ('islamabad', 48), ('bangladesh', 49), ('dhaka', 50), ('nepal', 51), ('kathmandu', 52), ('sri', 53), ('lanka', 54), ('colombo', 55), ('thailand', 56), ('bangkok', 57), ('malaysia', 58), ('kuala', 59), ('lumpur', 60), ('vietnam', 61), ('hanoi', 62), ('uae', 63), ('abu', 64), ('dhabi', 65), ('iran', 66), ('tehran', 67), ('iraq', 68), ('baghdad', 69), ('saudi', 70), ('arabia', 71), ('riyadh', 72), ('nigeria', 73), ('abuja', 74), ('kenya', 75), ('nairobi', 76), ('chile', 77), ('santiago', 78), ('who', 79), ('discovered', 80), ('gravity', 81), ('isaac', 82), ('newton', 83), ('invented', 84), ('telephone', 85), ('alexander', 86), ('graham', 87), ('bell', 88), ('h2o', 89), ('commonly', 90), ('called', 91), ('water', 92), ('which', 93), ('gas', 94), ('do', 95), ('plants', 96), ('absorb', 97), ('carbon', 98), ('dioxide', 99), ('planet', 100), ('known', 101), ('as', 102), ('red', 103), ('mars', 104), ('painted', 105), ('mona', 106), ('lisa', 107), ('leonardo', 108), ('da', 109), ('vinci', 110), ('largest', 111), ('ocean', 112), ('pacific', 113), ('developed', 114), ('theory', 115), ('relativity', 116), ('albert', 117), ('einstein', 118), ('ai', 119), ('short', 120), ('for', 121), ('artificial', 122), ('intelligence', 123), ('ml', 124), ('machine', 125), ('learning', 126), ('nlp', 127), ('natural', 128), ('language', 129), ('processing', 130), ('does', 131), ('cpu', 132), ('stand', 133), ('central', 134), ('unit', 135), ('ram', 136), ('computer', 137), ('memory', 138), ('gpu', 139), ('graphics', 140), ('a', 141), ('url', 142), ('web', 143), ('address', 144), ('http', 145), ('hypertext', 146), ('transfer', 147), ('protocol', 148), ('json', 149), ('used', 150), ('data', 151), ('exchange', 152), ('sql', 153), ('database', 154), ('query', 155), ('api', 156), ('mean', 157), ('application', 158), ('programming', 159), ('interface', 160), ('light', 161), ('bulb', 162), ('thomas', 163), ('edison', 164), ('airplane', 165), ('wright', 166), ('brothers', 167), ('penicillin', 168), ('fleming', 169), ('wrote', 170), ('hamlet', 171), ('william', 172), ('shakespeare', 173), ('harry', 174), ('potter', 175), ('j', 176), ('k', 177), ('rowling', 178), ('country', 179), ('land', 180), ('rising', 181), ('sun', 182), ('animal', 183), ('king', 184), ('jungle', 185), ('lion', 186), ('on', 187), ('earth', 188), ('blue', 189), ('whale', 190), ('bird', 191), ('cannot', 192), ('fly', 193), ('ostrich', 194), ('loyalty', 195), ('dog', 196), ('fruit', 197), ('typically', 198), ('apple', 199), ('yellow', 200), ('banana', 201), ('organ', 202), ('pumps', 203), ('blood', 204), ('heart', 205), ('humans', 206), ('breathe', 207), ('oxygen', 208), ('metal', 209), ('liquid', 210), ('at', 211), ('room', 212), ('temperature', 213), ('mercury', 214), ('instrument', 215), ('measures', 216), ('thermometer', 217), ('pressure', 218), ('barometer', 219), ('main', 220), ('portuguese', 221), ('spanish', 222), ('religion', 223), ('in', 224), ('islam', 225), ('national', 226), ('royal', 227), ('bengal', 228), ('tiger', 229), ('quick', 230), ('question', 231), ('you', 232), ('know', 233), ('i', 234), ('was', 235), ('wondering', 236), ('hey', 237), ('about', 238), ('this', 239), ('can', 240), ('tell', 241), ('me', 242)])

In [45]:
idx_to_word = { idx : word for word,idx in vocab.items()  }
idx_to_word

{0: '<UNK>',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: 'iraq',
 69: 'baghdad',
 70: 'saudi',
 71: 'arabia',
 72: 'riyadh',
 73: 'nigeria',
 74: 'abuja',
 75: 'kenya',
 76: 'nairobi',
 77: 'chile',
 78: 'santiago',
 79: 'who',
 80: 'discovered',
 81: 'gravity',
 82: 'isaac',
 83: 'newton',
 84: 'invented',
 85: 'telephone',
 86: 'alexander',
 87: 'graham',
 88: 'bell',
 89: 'h2o',
 90: 'commonly',
 91: 'called',
 92: 'water',
 93: 'which',
 94: 'gas',
 95: 'do',
 96: 'plants',
 97: 'absorb',
 98: 'carbon',
 99: 'dioxide',
 100: 'planet',
 101: 'known',
 102: 'as',
 103: 'red',
 104: 'mars',
 105: 'painted',
 106: 'mona',
 107: 'lisa',
 108: 'leonardo',
 109: 'da',
 110: 'vinci',
 111: 'largest',
 112: 'ocean',
 113: 'pacific',
 114: 'developed',
 115: 'theory',
 116: 'relativity',
 117: 'albert',
 118: 'einstein',
 119: 'ai',
 120: 'short',
 121: 'for',
 122: 'artificial',
 123: 'intelligence',
 124: 'ml',
 125: 'machine',
 126: 'learning',
 127: 'nlp',
 128: 'natural',
 129: 'language',
 130: 'processing',
 131: 'does',
 132: 'cpu',
 133: 'stand',
 134: 'central',
 135: 'unit',
 136: 'ram',
 137: 'computer',
 138: 'memory',
 139: 'gpu',
 140: 'graphics',
 141: 'a',
 142: 'url',
 143: 'web',
 144: 'address',
 145: 'http',
 146: 'hypertext',
 147: 'transfer',
 148: 'protocol',
 149: 'json',
 150: 'used',
 151: 'data',
 152: 'exchange',
 153: 'sql',
 154: 'database',
 155: 'query',
 156: 'api',
 157: 'mean',
 158: 'application',
 159: 'programming',
 160: 'interface',
 161: 'light',
 162: 'bulb',
 163: 'thomas',
 164: 'edison',
 165: 'airplane',
 166: 'wright',
 167: 'brothers',
 168: 'penicillin',
 169: 'fleming',
 170: 'wrote',
 171: 'hamlet',
 172: 'william',
 173: 'shakespeare',
 174: 'harry',
 175: 'potter',
 176: 'j',
 177: 'k',
 178: 'rowling',
 179: 'country',
 180: 'land',
 181: 'rising',
 182: 'sun',
 183: 'animal',
 184: 'king',
 185: 'jungle',
 186: 'lion',
 187: 'on',
 188: 'earth',
 189: 'blue',
 190: 'whale',
 191: 'bird',
 192: 'cannot',
 193: 'fly',
 194: 'ostrich',
 195: 'loyalty',
 196: 'dog',
 197: 'fruit',
 198: 'typically',
 199: 'apple',
 200: 'yellow',
 201: 'banana',
 202: 'organ',
 203: 'pumps',
 204: 'blood',
 205: 'heart',
 206: 'humans',
 207: 'breathe',
 208: 'oxygen',
 209: 'metal',
 210: 'liquid',
 211: 'at',
 212: 'room',
 213: 'temperature',
 214: 'mercury',
 215: 'instrument',
 216: 'measures',
 217: 'thermometer',
 218: 'pressure',
 219: 'barometer',
 220: 'main',
 221: 'portuguese',
 222: 'spanish',
 223: 'religion',
 224: 'in',
 225: 'islam',
 226: 'national',
 227: 'royal',
 228: 'bengal',
 229: 'tiger',
 230: 'quick',
 231: 'question',
 232: 'you',
 233: 'know',
 234: 'i',
 235: 'was',
 236: 'wondering',
 237: 'hey',
 238: 'about',
 239: 'this',
 240: 'can',
 241: 'tell',
 242: 'me'}

In [46]:
def predict(question_text,model,vocab,idx_to_word):
  model.eval()

  with torch.no_grad():
    indices = text_to_indices(question_text,vocab)

    if not indices:
      return "<UNK>"

    x = torch.tensor(indices).unsqueeze(0)  #batch size, sequence legth

    pred = torch.argmax(model(x),dim=1).item()


  return idx_to_word.get(pred,"<UNK>")

In [47]:
# Test
tests = [
    "What is the capital of France?",
    "What is H2O commonly called?",
    "Which planet is known as the red planet?",
    "Which bird cannot fly?",
    "What is the capital of Japan ?",

]
for q in tests:
    print(f"{q:45} → {predict(q, model, vocab, idx_to_word)}")

What is the capital of France?                → paris
What is H2O commonly called?                  → water
Which planet is known as the red planet?      → mars
Which bird cannot fly?                        → ostrich
What is the capital of Japan ?                → tokyo